parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
env:
  browser: true
  node: true
  es6: true
plugins:
  - prettier
  - flowtype
  - react
  - import
extends:
  - plugin:react/recommended
  - plugin:flowtype/recommended
  - plugin:import/errors
  - prettier
  - prettier/flowtype
  - prettier/react
  - prettier/standard
rules:
  # prettier
  prettier/prettier:
    - error
    -
      trailingComma: es5
      singleQuote: true
      semi: false
  # rules
  prefer-const: warn
  no-unused-vars:
    - error
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  no-multiple-empty-lines:
    - error
    - max: 1
  # react
  react/prefer-stateless-function: warn
  # import
  import/newline-after-import: error
  import/imports-first: error
