export const SIGN_UP = 'SIGN_UP'
export const SIGN_IN = 'SIGN_IN'
export const FAIL_SIGNIN = 'FAIL_SIGNIN'
export const SIGN_OUT = 'SIGN_OUT'
export const FETCH = 'FETCH'
export const FAIL_FETCH = 'FAIL_FETCH'
